services:
  - type: web
    name: fashion-api
    env: python
    buildCommand: ""
    startCommand: gunicorn api:app
    envVars:
      - key: PORT
        value: 10000

build:
  usePoetry: false
  environment:
    python: 3.10.10
