# -*- coding: utf-8 -*-
"""Model for Fashion MNIST dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZK35u6RJDDir5Z966Sr-4DSmRG2kJZM
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image


fashion_mnist = tf.keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

print(x_train.shape)

x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

print(x_train.shape)

model = keras.Sequential([
    keras.Input(shape=(28,28,1)),
    layers.Conv2D(32,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10,activation='softmax')
])

model.compile('adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.summary()

history = model.fit(x_train,y_train,batch_size=64,epochs=10,validation_split=0.2)

test_loss, test_acc = model.evaluate(x_test,y_test)
print(test_acc)

# Save an image from x_test to use with your API
img = x_test[0]  # Shape: (28, 28, 1)

# Remove the last channel dimension and convert from float32 to uint8
img = (img.squeeze() * 255).astype(np.uint8)

# Create a PIL image and save
img = Image.fromarray(img, mode='L')  # 'L' = grayscale
img.save("sample_image.png")
print("sample_image.png saved!")


model.save("fashion_model.keras", save_format="keras")



