name: Nightly batch predictions

on:
  schedule:
    - cron: '0 2 * * *'            # 02 :00 UTC daily
  workflow_dispatch:               # manual run button

jobs:
  batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run batch prediction
        env:
          API_URL: https://fashion-api-osw7.onrender.com/predict   # 🔑
        run: python batch_predict.py

      - name: Upload nightly CSV
        uses: actions/upload-artifact@v4
        with:
          name: batch_predictions
          path: batch_predictions_*.csv
